services:
  vault:
    image: {{.Image}}:{{.Tag}}
    container_name: vault
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_ADDR=http://localhost:8200
    ports:
      - "8080:8200"
    volumes:
      - vault-data:/vault/file

volumes:
  vault-data:
