services:
  nginx:
    image: nginx:latest
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.50"
          memory: 50M
        reservations:
          cpus: "0.25"
          memory: 20M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 10s
      update_config:
        parallelism: 1
        delay: 5s
        monitor: 5s
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        delay: 5s
        monitor: 5s
        order: stop-first
        failure_action: pause
    ports:
      - 8080:80
